"""evaluate_rl.py
================

Standalone RL evaluation for ALIS-WC checkpoints.

This script reproduces the RL evaluation protocol that produced the
ALIS-WC numbers reported in the paper. It loads a checkpoint via
``AttentionNet``, then calls ``Worker.run_episode`` on a list of benchmark
instances generated by ``generate_benchmarks_strict.py``.

The Worker codebase here is trained without a learned quantity head:
LOAD/UNLOAD quantities are deterministically set to the maximum
admissible value inside ``worker.py``. No ``force_full_load`` flag is
required at the API surface.

Usage
-----
::

    python evaluate_rl.py \\
        --model-path checkpoints/mdp_d10_noLTL_nopt_mhPPO_vNorm_ent0.005_s42.pth \\
        --benchmark-file evaluation_benchmarks.json \\
        --num-envs 5

The script writes a JSON results file (default name is timestamped).
"""

from __future__ import annotations

import argparse
import json
import os
import time
from typing import Any, Dict, List, Optional

import numpy as np
import torch

from parameters import EnvParams, TrainParams
from attention import AttentionNet
from env.task_env import TaskEnv
from worker import Worker


# 4-tier benchmark configurations matching the paper (Tables III / IV).
# Each tier fixes the per-instance dimensions; only the random seed varies.
BENCHMARK_CONFIGS = {
    "tier1": {
        "depots": 3,
        "species": 3,
        "agents_per_species": 3,
        "tasks": 15,
        "ltl_safety": 2,
        "ltl_sequential": 2,
    },
    "tier2": {
        "depots": 4,
        "species": 4,
        "agents_per_species": 4,
        "tasks": 40,
        "ltl_safety": 3,
        "ltl_sequential": 3,
    },
    "tier3": {
        "depots": 5,
        "species": 5,
        "agents_per_species": 5,
        "tasks": 65,
        "ltl_safety": 4,
        "ltl_sequential": 4,
    },
    "tier4": {
        "depots": 6,
        "species": 6,
        "agents_per_species": 6,
        "tasks": 100,
        "ltl_safety": 30,
        "ltl_sequential": 30,
    },
}


def _tier_to_env_ranges(tier_cfg: Dict[str, int]) -> Dict[str, Any]:
    """Convert a tier config to the env_param_ranges dict expected by the
    benchmark loop (single-value tuples to lock dimensions)."""
    return {
        "species_agents_range": [
            tier_cfg["agents_per_species"],
            tier_cfg["agents_per_species"],
        ],
        "species_range": [tier_cfg["species"], tier_cfg["species"]],
        "tasks_range": [tier_cfg["tasks"], tier_cfg["tasks"]],
        "depot_num_range": [tier_cfg["depots"], tier_cfg["depots"]],
    }


def _make_tier_benchmarks(
    tier: str, num_envs: int, seed_base: int = 1000
) -> List[Dict[str, Any]]:
    """Synthesise a list of tier-locked benchmark records (no LTL clauses)."""
    if tier not in BENCHMARK_CONFIGS:
        raise ValueError(
            f"Unknown tier '{tier}'. Choose one of {list(BENCHMARK_CONFIGS)}."
        )
    rng = np.random.default_rng(seed_base)
    seeds = [int(rng.integers(0, 2**31 - 1)) for _ in range(num_envs)]
    return [{"seed": s, "ltl_clauses": [], "env_info": {}} for s in seeds]


def build_worker(model_path: str, device: torch.device) -> Worker:
    """Create a Worker with a freshly-loaded model and a dummy env.

    The dummy env will be replaced per benchmark instance in
    :func:`run_one_benchmark`.
    """
    model = AttentionNet(
        agent_input_dim=TrainParams.AGENT_INPUT_DIM,
        task_input_dim=TrainParams.TASK_INPUT_DIM,
        embedding_dim=TrainParams.EMBEDDING_DIM,
    ).to(device)

    ckpt = torch.load(model_path, map_location=device, weights_only=False)
    state_dict = ckpt.get("best_model", ckpt.get("model"))
    if state_dict is None:
        raise KeyError(f"No 'model' or 'best_model' key in {model_path}")

    missing, unexpected = model.load_state_dict(state_dict, strict=False)
    if missing:
        print(
            f"[load_state_dict] missing keys: {len(missing)} (first 3: {missing[:3]})"
        )
    if unexpected:
        print(
            f"[load_state_dict] unexpected keys: {len(unexpected)} (first 3: {unexpected[:3]})"
        )
    model.eval()

    worker = Worker(
        mete_agent_id=0,
        local_network=model,
        local_baseline=None,
        global_step=0,
        device=str(device),
        save_image=False,
        seed=42,
        env_params=None,
    )
    return worker


def _ltl_clauses_to_worker_format(ltl_clauses: List[Any]) -> Optional[List[tuple]]:
    """Convert JSON-formatted LTL clauses to the (type, param1, param2)
    tuple list expected by ``Worker.run_episode``."""
    if not ltl_clauses:
        return None
    out: List[tuple] = []
    for c in ltl_clauses:
        if isinstance(c, dict):
            out.append((c.get("type"), c.get("param1"), c.get("param2")))
        elif isinstance(c, (list, tuple)) and len(c) >= 3:
            out.append((c[0], c[1], c[2]))
        else:
            raise ValueError(f"Unrecognised LTL clause format: {c!r}")
    return out


def run_one_benchmark(
    worker: Worker,
    benchmark: Dict[str, Any],
    env_param_ranges: Dict[str, Any],
    enable_ltl: bool,
) -> Dict[str, Any]:
    """Run the worker on a single benchmark instance, returning metrics."""
    seed = benchmark["seed"]
    raw_clauses = benchmark.get("ltl_clauses", []) if enable_ltl else []
    worker_ltl = _ltl_clauses_to_worker_format(raw_clauses)

    env = TaskEnv(
        per_species_range=tuple(env_param_ranges["species_agents_range"]),
        species_range=tuple(env_param_ranges["species_range"]),
        tasks_range=tuple(env_param_ranges["tasks_range"]),
        depot_num_range=tuple(env_param_ranges["depot_num_range"]),
        traits_dim=EnvParams.TRAIT_DIM,
        decision_dim=EnvParams.DECISION_DIM,
        max_task_size=EnvParams.MAX_TASK_SIZE,
        max_cargo_per_type=EnvParams.MAX_AGENT_CAPACITY,
        duration_scale=EnvParams.DURATION_SCALE,
        seed=seed,
        plot_figure=False,
    )
    env.init_state()
    worker.env = env

    t0 = time.time()
    result = worker.run_episode(
        training=False,
        sample=False,
        max_waiting=False,
        ltl_clauses=worker_ltl,
        constraint_mode_override="HARD",
    )
    elapsed = time.time() - t0

    # Worker.run_episode returns:
    #   (terminal_reward, episode_raw_return, buffer, perf_metrics, episode_truly_done)
    _, episode_return, _, perf_metrics, _ = result
    perf_metrics = perf_metrics or {}

    finished = sum(1 for t in env.task_dic.values() if t.get("finished", False))
    total = env.tasks_num
    completion = finished / total if total > 0 else 0.0

    def _scalar(key: str) -> Any:
        v = perf_metrics.get(key)
        if isinstance(v, (list, tuple)) and v:
            return v[0]
        return v

    return {
        "seed": seed,
        "num_agents": env.agents_num,
        "num_tasks": total,
        "num_depots": env.depots_num,
        "num_ltl_clauses": len(worker_ltl) if worker_ltl else 0,
        "finished_tasks": finished,
        "completion_rate": completion,
        "success": completion >= 0.99,
        "makespan": _scalar("makespan"),
        "travel_dist": _scalar("travel_dist"),
        "decision_steps": _scalar("decision_steps"),
        "episode_return": episode_return,
        "elapsed_time": elapsed,
    }


def summarise(results: List[Dict[str, Any]]) -> Dict[str, Any]:
    valid = [r for r in results if "error" not in r]
    n = len(valid)
    if n == 0:
        return {
            "error": "all evaluations failed",
            "num_evaluated": 0,
            "num_failed": len(results),
        }

    succ = sum(1 for r in valid if r["success"]) / n
    avg_completion = sum(r["completion_rate"] for r in valid) / n
    makespans = [r["makespan"] for r in valid if r["makespan"] is not None]
    travel = [r["travel_dist"] for r in valid if r["travel_dist"] is not None]
    return {
        "num_evaluated": n,
        "num_failed": len(results) - n,
        "success_rate": succ,
        "avg_completion_rate": avg_completion,
        "avg_makespan": float(np.mean(makespans)) if makespans else None,
        "avg_travel_dist": float(np.mean(travel)) if travel else None,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate an ALIS-WC checkpoint on a benchmark JSON."
    )
    parser.add_argument(
        "--model-path",
        default=None,
        help="Path to a single .pth checkpoint (single-seed evaluation). "
        "Mutually exclusive with --model-template.",
    )
    parser.add_argument(
        "--model-template",
        default=None,
        help="Path template containing literal '{seed}', expanded against --seeds "
        "for multi-seed aggregation. "
        "Example: 'ckpts/mdp_d10_noLTL_mhPPO_vNorm_ent0.005_s{seed}.pth'.",
    )
    parser.add_argument(
        "--seeds",
        default="",
        help="Comma-separated seed list (e.g. '42,142,242') used with "
        "--model-template to aggregate mean ± std across seeds.",
    )
    parser.add_argument(
        "--benchmark-file",
        default="evaluation_benchmarks.json",
        help="Benchmark JSON produced by generate_benchmarks_strict.py "
        "(ignored when --tier is provided)",
    )
    parser.add_argument(
        "--tier",
        choices=sorted(BENCHMARK_CONFIGS),
        help="Override --benchmark-file: use the four-tier paper "
        "configuration with locked dimensions and synthesised seeds.",
    )
    parser.add_argument(
        "--output-file",
        default=None,
        help="Where to write the per-instance results (default: timestamped)",
    )
    parser.add_argument(
        "--num-envs",
        type=int,
        default=None,
        help="Limit number of benchmarks to evaluate (default: all in JSON, "
        "or 30 when --tier is provided)",
    )
    parser.add_argument(
        "--enable-ltl",
        action="store_true",
        help="Apply LTL clauses from the benchmark JSON (if any)",
    )
    parser.add_argument(
        "--device", default="cuda" if torch.cuda.is_available() else "cpu"
    )
    args = parser.parse_args()

    # --- Resolve model paths (single vs multi-seed) ---
    if args.model_template and args.seeds:
        seed_list = [int(s.strip()) for s in args.seeds.split(",")]
        model_paths = [args.model_template.replace("{seed}", str(s)) for s in seed_list]
        multi_seed = True
    elif args.model_path:
        model_paths = [args.model_path]
        multi_seed = False
    else:
        parser.error("Provide either --model-path or --model-template + --seeds.")
        return  # unreachable

    # --- Resolve benchmark instances ---
    if args.tier is not None:
        tier_cfg = BENCHMARK_CONFIGS[args.tier]
        num_envs = args.num_envs if args.num_envs is not None else 30
        benchmarks = _make_tier_benchmarks(args.tier, num_envs)
        env_ranges = _tier_to_env_ranges(tier_cfg)
        bench_source = f"<synthesised tier '{args.tier}', {num_envs} seeds>"
    else:
        with open(args.benchmark_file) as f:
            bench_data = json.load(f)
        benchmarks = bench_data["benchmarks"]
        env_ranges = bench_data["config"]["env_params"]
        if args.num_envs is not None:
            benchmarks = benchmarks[: args.num_envs]
        bench_source = args.benchmark_file

    device = torch.device(args.device)

    # --- Run evaluation for each model seed ---
    all_summaries: List[Dict[str, Any]] = []

    for mi, model_path in enumerate(model_paths):
        if multi_seed:
            print(f"\n{'=' * 60}")
            print(f"[Seed {mi + 1}/{len(model_paths)}] {model_path}")
            print(f"{'=' * 60}")
        print(
            f"[evaluate_rl] device={device}, model={model_path}, "
            f"benchmarks={len(benchmarks)}, source={bench_source}, "
            f"enable_ltl={args.enable_ltl}"
        )

        worker = build_worker(model_path, device)

        results: List[Dict[str, Any]] = []
        for i, benchmark in enumerate(benchmarks):
            bseed = benchmark["seed"]
            print(
                f"[{i + 1:>3}/{len(benchmarks)}] seed={bseed} ... ", end="", flush=True
            )
            try:
                r = run_one_benchmark(worker, benchmark, env_ranges, args.enable_ltl)
                ms = f"{r['makespan']:.1f}" if r["makespan"] is not None else "N/A"
                print(
                    f"success={r['success']} completion={r['completion_rate']:.1%} "
                    f"makespan={ms} steps={r['decision_steps']}"
                )
                results.append(r)
            except Exception as exc:  # noqa: BLE001
                print(f"FAILED: {type(exc).__name__}: {exc}")
                results.append({"seed": bseed, "error": f"{type(exc).__name__}: {exc}"})

        summary = summarise(results)
        summary["model_path"] = model_path
        all_summaries.append(summary)

        print(f"\n--- Summary ({model_path}) ---")
        for k, v in summary.items():
            if isinstance(v, float):
                print(f"  {k}: {v:.4f}")
            else:
                print(f"  {k}: {v}")

    # --- Multi-seed aggregation ---
    if multi_seed and len(all_summaries) > 1:
        print(f"\n{'=' * 60}")
        print(f"Multi-seed aggregation ({len(all_summaries)} seeds)")
        print(f"{'=' * 60}")
        agg_keys = [
            "success_rate",
            "avg_completion_rate",
            "avg_makespan",
            "avg_travel_dist",
        ]
        for k in agg_keys:
            vals = [s[k] for s in all_summaries if s.get(k) is not None]
            if vals:
                m, s = float(np.mean(vals)), float(np.std(vals))
                print(f"  {k}: {m:.4f} ± {s:.4f}")

    # --- Save results ---
    output_file = args.output_file or (
        f"eval_results_{'ltl' if args.enable_ltl else 'no_ltl'}_{int(time.time())}.json"
    )
    payload: Dict[str, Any] = {
        "config": {
            "model_paths": model_paths,
            "benchmark_file": args.benchmark_file,
            "tier": args.tier,
            "enable_ltl": args.enable_ltl,
            "num_envs": len(benchmarks),
            "device": str(device),
        },
        "per_seed_summaries": all_summaries,
    }
    if multi_seed and len(all_summaries) > 1:
        agg = {}
        for k in [
            "success_rate",
            "avg_completion_rate",
            "avg_makespan",
            "avg_travel_dist",
        ]:
            vals = [s[k] for s in all_summaries if s.get(k) is not None]
            if vals:
                agg[k] = {"mean": float(np.mean(vals)), "std": float(np.std(vals))}
        payload["aggregated"] = agg

    with open(output_file, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"\nResults saved to: {output_file}")


if __name__ == "__main__":
    main()
